shaper_related

In [7]:
import tensorflow as tf
X = tf.placeholder("float", [None, 5,1])
print(tf.shape(tf.squeeze(X, -1))) 
print(tf.shape(X))
print(X.shape)
print(tf.squeeze(X, -1).shape)
print(X[:,:,0].shape)

Tensor("Shape_9:0", shape=(2,), dtype=int32)
Tensor("Shape_10:0", shape=(3,), dtype=int32)
(?, 5, 1)
(?, 5)
(?, 5)


In [50]:
import tensorflow as tf
from tensorflow.python.layers.core import Dense
vocab_size = 200000

batch_size = 50
Batch = 50
text_feature_dim = 4097
input_embedding_size = 200  # character length
decoder_hidden_units = 1024
encoder_inputs = tf.placeholder(shape=(Batch, None), dtype=tf.int32, name='encoder_inputs')
decoder_inputs = encoder_inputs
decoder_start_token = tf.ones(shape=[batch_size, 1], dtype=tf.int32) * 1  # data_utils.start_token
decoder_inputs_train = tf.concat([decoder_start_token, decoder_inputs], axis=1)
encoder_final_state_c = tf.placeholder(shape=(Batch, text_feature_dim), dtype=tf.float32,
                                               name='encoder_final_state')
context_layer = Dense(input_embedding_size, dtype=tf.float32, name='context_layer')
context_input = context_layer(encoder_final_state_c)
context_input_1 = tf.reshape(context_input,[-1,1,input_embedding_size])
max_len_inputs = tf.shape(encoder_inputs)[1] + 1
context_input_tile = tf.tile(context_input_1,[1,max_len_inputs,1])
embeddings = tf.Variable(tf.random_uniform([vocab_size, input_embedding_size], -1.0, 1.0), dtype=tf.float32)
decoder_embeddings = embeddings
decoder_inputs_embedded = tf.nn.embedding_lookup(params=decoder_embeddings, ids=decoder_inputs_train)
input_layer = Dense(decoder_hidden_units, dtype=tf.float32, name='input_projection')
decoder_inputs_embedded_fn = input_layer(decoder_inputs_embedded)


(50, ?)
(50, 200)
(50, ?, 200)
(50, ?, 1024)
(50, ?, 200)


#how to deal with batch size and layers
#conv layer
tf.layers.conv2d
[batch_size, image_width, image_height, channels]
will perform convolution on the last three dimensions
#dense layer
Dense
will perform fully connected on the last dimension(see its initial)
outputs = activation(inputs * kernel + bias)
self.kernel shape=[input_shape[-1].value, self.units]

In [48]:
#add one dimension
context_input_1 = tf.reshape(context_input, [-1, 1, input_embedding_size])
print(context_input_1.shape)

(50, 1, 200)


In [49]:
#tile feature
context_input_tile =  tf.tile(context_input_1,[1,5,1])
print(context_input_tile.shape)

(50, 5, 200)


In [14]:
#concat features
decoder_input_final = tf.concat([context_input_tile, decoder_inputs_embedded], 2)
print(decoder_input_final.shape)

(50, ?, 400)


In [47]:
#create same shape ones
import numpy as np
a = tf.placeholder(shape=(None, 3), dtype=tf.int32, name='inputs')
#a.get_shape() need to have specific shape
a_shape = tf.shape(a)
c = tf.ones(tf.shape(a))
print(a_shape)
d = tf.ones(shape = [5,a_shape[0]])
sess = tf.InteractiveSession()
d_o = sess.run(d,feed_dict={a:np.ones([3,3])})
print(d_o)

Tensor("Shape_20:0", shape=(2,), dtype=int32)
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [ ]:
#temporary save
weight_dir = './weight_fn_1de_input_context/'

context_layer = Dense(input_embedding_size, dtype=tf.float32, name='context_layer')

context_input = context_layer(encoder_final_state_c)
context_input_1 = tf.reshape(context_input,[-1,1,input_embedding_size])
max_len_inputs = tf.shape(encoder_inputs)[1] + 1
context_input_tile = tf.tile(context_input_1,[1,max_len_inputs,1])

 decoder_inputs_embedded_concat = tf.concat([decoder_inputs_embedded,context_input_tile],2)
    