In [1]:
import tensorflow as tf
import numpy as np
X = tf.placeholder("float", [None, 5])
print(X.shape)
X1 = X * 0.3
neg_X1 = 1 - X1
#X1_sum = X1 + neg_X1
X1_log = tf.log(X)
nX1_log = tf.log(neg_X1)
B = np.ones([3,5])*0.6
Out = -tf.multiply(X1_log,B)-tf.multiply(nX1_log,1-B)
Loss = tf.reduce_sum(Out)
sess = tf.InteractiveSession()
feed_X = np.ones([3,5])
tf.global_variables_initializer().run()
log_o = tf.log(1/(1e30))
oo = sess.run((Loss), feed_dict={X:feed_X })
log_oo = sess.run(log_o)
#print(oo)
print(log_oo)


/Users/kaijia/openai_gym_python3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


(?, 5)
-69.0776


In [7]:
nB = 1-B
print(nB)

[[ 0.4  0.4  0.4  0.4  0.4]
 [ 0.4  0.4  0.4  0.4  0.4]
 [ 0.4  0.4  0.4  0.4  0.4]]


In [5]:
1/(1e10)

1e-10